### ISSUE TITLE
invalid N, check instance (urgency for me)

### ISSUE THREAD

**Issue by yyyyysh0** [Kei18/lacam3#3]
[8x8map.txt](https://github.com/user-attachments/files/16703340/8x8map.txt)
[8x8scen.txt](https://github.com/user-attachments/files/16703341/8x8scen.txt)
(github doesn't allow uploading ".map" and ".scen" files, so I changed their names)
In an example with eight instances, when I type "build/main -i assets/8x8.scen -m assets/T1/8x8.map -N 8 -v 2", it says "invalid N, check instance". Then I gradually decrease N until it works correctly at 5. Later I created a 4x4 that had no such problem and could correctly identify N=2. Of course, there is no such problem with "random-32-32-10.map" and "random-32-32-10-random-1.scen".

**Comment by Kei18** [comment]
Hi, 

Please check the scenario file, e.g., (1, 7) is an invalid start position (bottom left).

```
1	8x8.map	8	8	1	7	3	3	0
```

![screenshot-2024-08-22-11-16-07-839](https://github.com/user-attachments/assets/f2a207e8-d58d-4b3c-a308-60b6321333ea)

The scenario loader skips reading such invalid positions.

**Comment by yyyyysh0** [comment]
Thank you very much! I thought the vertical direction was i and the horizontal direction was j (like the read order of the two-dimensional array x[i][j]).

**Comment by yyyyysh0** [comment]
So the direction is first horizontal and then vertical →↓ in lacam3, right? (I don't want to confuse people looking at this issue)

**Comment by Kei18** [comment]
You are right. I'm following the MAPF benchmark format:
https://movingai.com/benchmarks/mapf.html

**Comment by yyyyysh0** [comment]
Thank you again for your help.
By the way, If I wish to incorporate certain conditions, such as the robot vanishing upon arrival, the robot being smaller than the target, the robot's traversal order having been fixed, etc., how should I modify it? That is, are there any additional parameters to employ or where is the code for handling the logic?

**Comment by yyyyysh0** [comment]
OK. Anyway, thanks for your reply!

**Comment by yyyyysh0** [comment]
I want to know what the meaning of the first and last number of each line in the ".scen" file is, it seems that any number can be used instead.

**Comment by Kei18** [comment]
It's originally from the single-agent pathfinding benchmark, and for MAPF these two values have no strong meaning. Check this page:
https://movingai.com/benchmarks/formats.html
