### ISSUE TITLE
Question about the mechanism and position of monte-carlo configuration generator

### ISSUE THREAD

**Issue by ShuaiZhou302** [Kei18/lacam3#4]
Hello sir!
The section 4 monte carlo configuration generator in the paper Engineering lacam* is pretty short and i am not quite get how this part work and how to generate parallel configuration?
And when i try to find it in the implementation , i didn't sure where is it and how it work in the planner.cpp part (if i guess it right, it is in this function?)
![image](https://github.com/user-attachments/assets/128b8fd5-ffce-4f73-aa62-370182426a50)
would you be so kind to explain the monte-carlo configure generation method, or if you have a recorded talk, I can learn from it.
thank you so much

**Comment by Kei18** [comment]
Hi, some explanations are in the slide:
https://speakerdeck.com/kei18/engineering-lacam-star-towards-real-time-large-scale-and-near-optimal-multi-agent-pathfinding?slide=22

The screenshot part is correct. Basically, it executes PIBT multiple times with different seeds, and extracts the best.

**Comment by ShuaiZhou302** [comment]
Thank you, got it
