### ISSUE TITLE
customize connectivity constraints

### ISSUE THREAD

**Issue by worldlyesterday** [Kei18/lacam3#5]
Thanks for your impressive work! 
I'm trying to utilize this method on a warehouse system. Because some agents have orbits, they have to move horizontally or vertically. So I'm wondering if it is possible and how to customize some connectivity constraints on the MAPF graph. I have tried to alter the graph generation process(graph.cpp), but it seems to result in invalid solution(against the connectivity constraints).
Your reply will be highly appreciated!

**Comment by Kei18** [comment]
It seems that what you need is to remove the corresponding edges from `Vertex.neighbor’, as you tried. Please check again or tell me the errors you encountered.

**Comment by Kei18** [comment]
Could you try the same thing with the original repo?
https://github.com/Kei18/lacam
As lacam3 introduces many techniques, the above may be easier for you to debug. You can also try py-lacam:
https://github.com/Kei18/py-lacam

Sorry, I do not have time to provide further help at the moment.
